export const TOP_PROJECTS_DATA = [
  {
    title: "Quick Doodle",
    tags: ["MERN", "NextJs", "Web Sockets", "TypeScript"],
    desc: "🎨 QuickDoodle is a real-time multiplayer drawing & guessing web app inspired by Skribbl.io — fast, simple, and modern. Draw on a shared canvas or solve creative riddles. Compete in private rooms with friends or join global public rooms to play with anyone. 🧠 Future plans: AI agent bots that can guess drawings, learn over time, and solo play.",
    link: "https://quick-doodle.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/Quick_Doodle",
    image: "/quick_doodle.png",
  },
  {
    title: "Glb Viewer",
    tags: ["NextJs", "ThreeJs", "TypeScript"],
    desc: "A simple and fast GLB viewer that lets you test 3D models both on and off the body. The app includes default body models, making it easy to preview how your assets look in real scenarios. Perfect for quick checks, prototyping, and visual testing.",
    link: "https://glb-model-viewer-tau.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/glb-viewer",
    image: "/glb_viewer.png",
  },
  {
    title: "Testimonials WebApp",
    tags: ["MERN"],
    desc: "Inspired by Testimonials.to, this MERN-based platform helps businesses easily collect, save, and showcase client testimonials. It streamlines gathering and displaying feedback on websites and other digital platforms. Currently, the project is focused on integrating video reviews to enhance how clients share their experiences.",
    link: "https://testimonials-mern-app.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/testimonials",
    image: "/testimonials_page.png",
  },
  {
    title: "GROK Shooting Star",
    tags: ["HTML", "CSS", "Canvas", "JavaScript"],
    desc: "A lightweight HTML5 canvas animation that creates a rotating starfield with flickering stars and occasional shooting stars. Fully customizable — adjust star size, glow, speed, and quantity with simple JavaScript tweaks. Perfect for backgrounds, hero sections, or interactive visual effects.",
    link: "https://usmandevcraft.github.io/grok-shooting-stars/",
    github_link: "https://github.com/UsmanDevCraft/grok-shooting-stars",
    image: "/grok_star_effect.png",
  },
];

export const ACCORDION_PROJECTS_DATA = [
  {
    title: "E-Commerce WebApp",
    tags: ["MERN"],
    desc: "This is an e-commerce store webapp which allows users to search for different products, save the product to thier cart, and provides login and signup functionality. This webapp is made from Reactjs, Bootstrap, Pexels API, MERN for login and signup and localstorage for storing cart.",
    link: "https://e-commerce-store-web-app.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/e-commerce",
    image: "/ecommerce_img_001.png",
  },
  {
    title: "Pexels Clone",
    tags: ["ReactJs", "BootStrap", "Pexels API"],
    desc: "This is a clone of image gallery PEXELS which allows users to search all category images and videos and download them too for free. This app is made from HTML, CSS, JavaScript, ReactJS, BootStrap, Pexels API and hosted on vercel.",
    link: "https://pexels-clone-web-app.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/Pexels-Clone",
    image: "/pexels_clone_img_001.png",
  },
  {
    title: "Realtime Device Tracker",
    tags: ["NodeJs", "Socket.io"],
    desc: "This project is a real-time device tracking system, developed using Node.js, Express.js, Socket.IO, and Leaflet. It efficiently tracks and displays device locations in real-time on an interactive map. The system leverages WebSockets for seamless, real-time communication between the server and clients.",
    link: "https://realtime-device-tracker-system.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/realtime-device-tracker",
    image: "/device-tracker_ss.png",
  },
  {
    title: "QR Code Generator",
    tags: ["NodeJs"],
    desc: "This application is a URL to QR Code converter built using HTML, Node.js, and Express.js. Users can effortlessly input any URL into a form, convert it into a QR code, and download the QR code image.",
    link: "https://url-to-qr-code-convertor-generator-5izt2bsmr.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/QR-Generator",
    image: "/qr-code-gen_ss.png",
  },
  {
    title: "Cloudbook",
    tags: ["MERN"],
    desc: "This is an online notes saving web app which is used to store the data of a specific user only. Using the Login and Signup functionality, one can easily create an account and login to create, read, update, and delete their notes. This is made from React + Vite, MongoDB, Express, and Node, and Bootstrap.",
    link: "https://cloud-book-mern-web-app.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/Cloudbook",
    image: "/cloudbook_ss_3.png",
  },
  {
    title: "Modern-Website-Landing-Page",
    tags: ["HTML, CSS, JS, GSAP"],
    desc: "This is a modern website landing page with great animations and effects coded with pure HTML, CSS and vanilla JS. It also contains GSAP for some effects.",
    link: "https://usmandevcraft.github.io/Modern-Website-Landing-Page/",
    github_link: "https://github.com/UsmanDevCraft/Modern-Website-Landing-Page",
    image: "/Modern_Web_Landing_Page_001.png",
  },
  {
    title: "textEditor",
    tags: ["ReactJs"],
    desc: "This is a text editor which can be used for text editing. It is made from react, bootstrap and vite.",
    link: "https://text-editor-gold-nine.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/textEditor",
    image: "/TextEditor_001.png",
  },
  {
    title: "NewsHub",
    tags: ["ReactJs"],
    desc: "A news website to deliver news up to date. This is developed using ReactJs, Bootstrap, News API and hosted on vercel.",
    link: "https://news-hub-news-delivering-website.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/NewsHub",
    image: "/NewsHub_ss_01.png",
  },
  {
    title: "SNAKE-GAME",
    tags: ["HTML, CSS, JS"],
    desc: "This is a responsive snake game provided with different speed options to play with. It is coded with pure HTML, CSS and vanilla JS.",
    link: "https://usmandevcraft.github.io/SNAKE-GAME/",
    github_link: "https://github.com/UsmanDevCraft/SNAKE-GAME",
    image: "/Snake_Game_001.png",
  },
  {
    title: "Responsive-SPOTIFY-Clone",
    tags: ["HTML, CSS, JS"],
    desc: "This is a responsive music app with great animations coded with pure HTML, CSS and Vanilla JS.",
    link: "https://usmandevcraft.github.io/Responsive-SPOTIFY-Clone/",
    github_link: "https://github.com/UsmanDevCraft/Responsive-SPOTIFY-Clone",
    image: "/spotify_clone_ss.png",
  },
  {
    title: "Responsive-BUBBLE-GAME",
    tags: ["HTML, CSS, JS"],
    desc: "This is a responsive bubble game in which you hit bubbles with same number as that of hit targtet given, each correct hit gives a score of 10 and after each hit, all numbers on screen changes with change in target. It is made with HTML, CSS and JS only.",
    link: "https://usmandevcraft.github.io/Responsive-BUBBLE-GAME/",
    github_link: "https://github.com/UsmanDevCraft/Responsive-BUBBLE-GAME",
    image: "/bubble_game_ss.png",
  },
  {
    title: "DocsApp",
    tags: ["ReactJs, TailwindCSS, Framer Motion"],
    desc: "This is a modern web design for a mini document app with draggable notes cards. It is built with help of React, Tailwind and Framer motion.",
    link: "https://docs-app-sigma.vercel.app/",
    github_link: "https://github.com/UsmanDevCraft/DocsApp",
    image: "/docs_app_001.png",
  },
];
